### PR TITLE
#1675: Fix feature images being styled as thumbnails

### LINKED ISSUE #1675: Feature Images on Item show page are being styled as Thumbnails
From #1666 

We displaying this feature image as a "thumbnail" on Item show page which has the following css:

```css
.j-thumbnail {
    max-width: 135px;
    max-height: 175px;
}
```

But we have more real-estate to work with here? Should we increase the size of these feature
images on the show page, so users can view the image better?

This actually appears to be a regression. We were originally styling them as feature images
before using the following css: https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/javascript/styles/image.scss#L6-L9. But when we added the fallback image about 9 months ago, we changed everything (including the feature images) to be styled as thumbnails (`.j-thumbnail`)

### PR DESCRIPTION
**Pull request by murny**
Fixes #1675

Feature Image now takes up far more real estate and easier to see. What this looks like:

image

Question: We resize our images (via activestorage/imagemagick) and set html width/height to be 350x350 for feature images and 100x100 for thumbnails. However for CSS we set a max-width/max-height for these differently as 270x350 for feature images and 135x175 for thumbnails. So not sure why these are different? We set these max widths as a solution for this issue : https://github.com/ualbertalib/jupiter/issues/661. But curious since we are forcing a resize via imagemagick if this is doing what we think it is (if the images are always going to be 100x100 or 350x350 since we resize them, then our max-width/max-height CSS will force them into different dimensions which could hurt the image quality)? 

Also in Rails 6 there appears to be better/improved resize methods we should maybe look into (#resize_to_fit, #resize_to_fill)

### CODE REVIEW

File: app/helpers/images_helper.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ def file_icon(content_type)
   end
 
   def safe_thumbnail_tag(thumbnail, image_tag_options)
-    image_tag_options[:class] = 'j-thumbnail img-thumbnail'
+    image_tag_options[:class] ||= 'j-thumbnail img-thumbnail'
     image_tag_options[:onerror] = "this.onerror=null;this.src='#{
       asset_pack_url('media/images/era-logo-without-text.png')
     }';"
```
Comment (pgwillia) [inline app/helpers/images_helper.rb:32]: Nice!  Would there be any advantage to memoizing the `:onerror ` option as well?

File: app/views/application/_feature_image.html.erb [hunk 2]
```diff
@@ -1,6 +1,9 @@
 <% if policy(object).thumbnail? %>
   <% if thumbnail_path(object&.thumbnail_file).present? %>
-    <%= safe_thumbnail_tag(thumbnail_path(object&.thumbnail_file, resize: '350x350', auto_orient: true), alt: '', size: '350x350') %>
+    <%= safe_thumbnail_tag(thumbnail_path(object&.thumbnail_file, resize: '350x350', auto_orient: true),
+                           alt: '',
+                           size: '350x350',
+                           class: 'j-feature-image img-thumbnail') %>
```
Comment (pgwillia) [inline app/views/application/_feature_image.html.erb:6]: 👍

File: app/helpers/images_helper.rb (hunk 1 above)
Comment (murny) [reply app/helpers/images_helper.rb:32]: I can't really image a usecase where we would want to override this? I guess if we do have a usecase, we can do it then is my thinking 🤔

**Comment by pgwillia** [comment]
I think you're right about that what we're doing could hurt the image quality.  [Reading the docs](https://github.com/janko/image_processing/blob/master/doc/minimagick.md#methods) it looks like what we really want is #resize_to_fit or #resize_to_limit rather than just resize.

**Comment by murny** [comment]
Makes me wonder if `.resize` is doing the correct thing? Seems like its a valid method if your using 
`minimagick` gem but not for `image_processing` (which jupiter is currently using)?

So definitely think we need to switch to one of the methods from `image_processing`. Just the question is which one? 

They all seem pretty similar with minor differences:

- `#resize_to_limit` resizes only when its larger
- `#resize_to_fit` will downsize if image is larger and upsize if smaller
- `#resize_to_fill` will crop the image in the larger dimension (default is crop center)

So probably we want `#resize_to_limit` 🤔

File: app/helpers/images_helper.rb (hunk 1 above)
Comment (pgwillia) [reply app/helpers/images_helper.rb:32]: I just realized that I didn't understand the significance of this before.  It enables the other change you made so that sometimes it can be `j-feature-image`.  

Then I was thinking that maybe it would be useful for addressing the different cases where we do this https://github.com/ualbertalib/jupiter/blob/d804d8c7c2856feffa84c5758c87421325708acd/app/views/application/_thumbnail.html.erb#L7-L12 but then I realized that this isn't the same thing.  We want the javascript there to clean up the image 500 errors.

Comment (pgwillia) [reply app/helpers/images_helper.rb:32]: In conclusion, there is no advantage to memoizing the `:onerror` option.

**Comment by mbarnett** [comment]
I would imagine that what we would want is `resize_to_limit` (or `resize_to_fit` if we happen to have a bunch of files smaller than 270x350? Also agree that how we gen the thumbnails should probably match the CSS, or we're likely running into artifacts?

**Comment by murny** [comment]
Makes sense 👍. 
I'll submit a different PR for converting our `resize` to `resize_to_limit`. 

I will also change our css a tad. My thinking is thumbnails should match html/resize, so lets make max-width/max-height the same, so 100px for each?

For Feature images we have to be a bit more careful due to responsiveness nature of the sidebar (the width will dynamically change on screen size). So max-width im curious what the best solution. I'm leaning towards using `max-width: 100%` then setting a `max-height: 350px`.  The other option is defining breakpoints (on Large screens its max-width: 350px but on any screen smaller its 100%?). We will have to play around with this though 🤔 

Will merge this PR as is though. Thanks for thoughful feedback 👍
